### ISSUE TITLE
Aakash Portfolio Review

### ISSUE THREAD

**Issue by GordonOtieno** [skyv26/portfolio#20]
## Required Changes
- Please add validations and button borders on active and hover to your form, adding this will help draw the attention of users.
- Please implement figma design fonts for nice appearance.
- Text area fonts should inherit the figma design fonts.

**Comment by skyv26** [comment]
@GordonOtieno Thank you for your nice feedback 👍🏻 
I have successfully updated my code as per required changes mentioned above.
