### ISSUE TITLE
Issues raised in the morning session

### ISSUE THREAD

**Issue by John-Kibirige** [skyv26/portfolio#22]
## Raised on 22/7/2022
- Kindly adjust the form area on your desktop version to take up more space compared to the text in the same container according to the Figma template
- Please use separate placeholder text for both mobile and desktop so that the mobile popup doesn't look to be overcrowded
- Kindly endeavor to change one of the button links on your popup card as they look the same which is also different from the Figma template

**Comment by skyv26** [comment]
# Hi @John-Kibirige ,

Thank you for your awesome feedback and I really like the way you point out the issues by checking my work details. Well I am planning for creating new portfolio. I will soon deploy the `Portfolio-v2`. Please feel free to share your thoughts.

Happy Coding 🥂
